version: '3'

services:
  haproxy-consul:
    container_name: otus_sn_dialog_haproxy
    image: emmetog/haproxy-consul
    environment:
      - CONSUL_SERVER=consul-node1
    networks:
      - otus_sn_network
    volumes:
      - ./docker/haproxy/haproxy.template:/etc/haproxy/haproxy.template:ro
    depends_on:
      - consul-agent_1
      - consul-agent_2
    ports:
      - "7000:7000"
  consul-agent_1:
    image: bitnami/consul:1.12.0
    environment:
      - CONSUL_BOOTSTRAP_EXPECT=0
      - CONSUL_CLIENT_LAN_ADDRESS=0.0.0.0
      - CONSUL_DISABLE_KEYRING_FILE=true
      - CONSUL_RETRY_JOIN_ADDRESS=consul-node1
      - CONSUL_ENABLE_UI=false
      - CONSUL_AGENT_MODE=client
    networks:
      - otus_sn_network
    volumes:
      - ./docker/consul/dialog1.json:/opt/bitnami/consul/conf/dialog.json
    depends_on:
      - dialog-service_1
  consul-agent_2:
    image: bitnami/consul:1.12.0
    environment:
      - CONSUL_BOOTSTRAP_EXPECT=0
      - CONSUL_CLIENT_LAN_ADDRESS=0.0.0.0
      - CONSUL_DISABLE_KEYRING_FILE=true
      - CONSUL_RETRY_JOIN_ADDRESS=consul-node1
      - CONSUL_ENABLE_UI=false
      - CONSUL_AGENT_MODE=client
    networks:
      - otus_sn_network
    volumes:
      - ./docker/consul/dialog2.json:/opt/bitnami/consul/conf/dialog.json
    depends_on:
      - dialog-service_2
  dialog-service_1:
    container_name: otus_sn_dialog_service_1
    build:
      context: .
    restart: on-failure
    networks:
      - otus_sn_network
      - internal
    depends_on:
      - proxysql
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
  dialog-service_2:
    container_name: otus_sn_dialog_service_2
    build:
      context: .
    restart: on-failure
    networks:
      - otus_sn_network
      - internal
    depends_on:
      - proxysql
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
  proxysql:
    container_name: otus_dialog_proxysql
    image: proxysql/proxysql:2.0.13
    volumes:
      - ./docker/proxysql/proxysql.cnf:/etc/proxysql.cnf
    ports:
      - "16032:6032"
      - "16033:6033"
      - "16070:6070"
    networks:
      - internal
    depends_on:
      - shard1
      - shard2
      - shard3
  shard1:
    container_name: otus_dialog_shard1
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: otus
    volumes:
      - ./docker/mysql/scripts:/docker-entrypoint-initdb.d
      - ./docker/mysql/shard1_data:/var/lib/mysql
    ports:
      - "3310:33061"
    networks:
      - internal
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
  shard2:
    container_name: otus_dialog_shard2
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: otus
    volumes:
      - ./docker/mysql/scripts:/docker-entrypoint-initdb.d
      - ./docker/mysql/shard2_data:/var/lib/mysql
    ports:
      - "3311:33061"
    networks:
      - internal
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
  shard3:
    container_name: otus_dialog_shard3
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: otus
    volumes:
      - ./docker/mysql/scripts:/docker-entrypoint-initdb.d
      - ./docker/mysql/shard3_data:/var/lib/mysql
    ports:
      - "3312:33061"
    networks:
      - internal
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
networks:
  internal:
    driver: bridge
  otus_sn_network:
    external: true