version: '3'

services:
  dialog-service:
    container_name: otus_sn_dialog_service
    build:
      context: .
    restart: on-failure
    ports:
      - "7000:7000"
    networks:
      - otus_sn_network
      - internal
    depends_on:
      - proxysql
  proxysql:
    container_name: otus_dialog_proxysql
    image: proxysql/proxysql:2.0.13
    volumes:
      - ./docker/proxysql/proxysql.cnf:/etc/proxysql.cnf
    ports:
      - "16032:6032"
      - "16033:6033"
      - "16070:6070"
    networks:
      - internal
    depends_on:
      - shard1
      - shard2
      - shard3
  shard1:
    container_name: otus_dialog_shard1
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: otus
    volumes:
      - ./docker/mysql/scripts:/docker-entrypoint-initdb.d
      - ./docker/mysql/shard1_data:/var/lib/mysql
    ports:
      - "3310:33061"
    networks:
      - internal
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
  shard2:
    container_name: otus_dialog_shard2
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: otus
    volumes:
      - ./docker/mysql/scripts:/docker-entrypoint-initdb.d
      - ./docker/mysql/shard2_data:/var/lib/mysql
    ports:
      - "3311:33061"
    networks:
      - internal
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
  shard3:
    container_name: otus_dialog_shard3
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: otus
    volumes:
      - ./docker/mysql/scripts:/docker-entrypoint-initdb.d
      - ./docker/mysql/shard3_data:/var/lib/mysql
    ports:
      - "3312:33061"
    networks:
      - internal
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
networks:
  internal:
    driver: bridge
  otus_sn_network:
    external: true